---
- name: Debian - Update and Install Packages
  ansible.builtin.apt:
    name: "{{ baseline_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Debian - Install Python Management Libraries
  ansible.builtin.pip:
    name: [kubernetes, pyyaml, jsonpatch]
    state: present
    executable: pip3
