---
- name: RedHat - Update and Install Packages
  ansible.builtin.dnf:
    name: "{{ baseline_packages }}"
    state: present
    update_cache: yes

- name: RedHat - Install Python Management Libraries
  ansible.builtin.pip:
    name: 
      - kubernetes
      - pyyaml
      - jsonpatch
    state: present
    executable: pip3
    extra_args: --break-system-packages 
