
baseline_swappiness: 5

baseline_packages:
  - git
  - curl
  - wget
  - vim
  - nano
  - net-tools
  - htop
  - unzip
  - tree
  - python3-pip
  - software-properties-common
  - ca-certificates
  - gnupg2
  - jq
  - rsync
  - dnsutils
  - apt-transport-https
  - bash-completion
  - lsof            

